name: CI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache the build
        uses: actions/cache@v2
        id: restore-build
        with:
          key: build-${{ github.sha }}
          path: ./*
          restore-keys: build-${{ github.sha }}

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{secrets.KNOWN_HOSTS}}

      - name: Restore the cached build
        uses: actions/cache@v2
        id: restore-build
        with:
          key: build-${{ github.sha }}
          path: ./*

      - name: Set Git Config
        run: |
          git config --global user.email "${{secrets.EMAIL}}"
          git config --global user.name "Github Actions"
          git config http.postBuffer 524288000

      - name: Commit built files
        run: |
          git add . -f
          git commit -m "Automated deployment: ${{github.sha}}" --amend --no-edit --quiet

      - name: Add git remote
        run: |
          git add origin jordanme.co.uk@ssh.stackcp.com:git_repos/space-tourism.git

      - name: Push Live
        run: |
          git pull main

